version: "3.2"
services:
  httpd:
    image: python:3.7-alpine
    volumes:
      - ./httpd:/opt/app
      - ./rootfs/var/www:/var/www
    working_dir: /opt/app
    ports:
      - "8080:8080"
    command: ["python", "httpd.py", "-a", "0.0.0.0", "-p", "8080"]
  ab:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - httpd
    command: ["/tmp/wait-for-it.sh", "httpd:8080", "--", "/usr/bin/ab", "-n", "50000", "-c", "100", "-r", "http://httpd:8080/"]
