version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./tests:/opt/tests
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    command: ["python", "app.py"]
  redis:
    image: redis:4.0.11

volumes:
  tests: